### ISSUE TITLE
Responsiveness Issue (1024x768)

### ISSUE THREAD

**Issue by Furyforev3r** [matheuspergoli/draftcode#2]
![image](https://github.com/matheuspergoli/draftcode/assets/88341564/77ff59ea-b1b1-49a7-87d9-c5717ca1437d)

**Comment by matheuspergoli** [comment]
![image](https://github.com/matheuspergoli/draftcode/assets/94739199/809b6883-11e2-4c6c-8ac0-18c5d401d143)

Aqui está normal

**Comment by Furyforev3r** [comment]
Here there is a problem **rendering** the image ("Draft Code Hero Image React") and it is exceeding the maximum width of the content... Try adjusting its proportions using % or try adjusting using Flex.
![image](https://github.com/matheuspergoli/draftcode/assets/88341564/a67dc63e-ba54-4126-b729-8fbfa52a8b9a)

**Comment by Furyforev3r** [comment]
It worked to adjust the maximum width!
![image](https://github.com/matheuspergoli/draftcode/assets/88341564/7d549da6-832f-453f-8c1e-71254c2f1f3c)

**Comment by Furyforev3r** [comment]
It worked to adjust the maximum width!
![image](https://github.com/matheuspergoli/draftcode/assets/88341564/7d549da6-832f-453f-8c1e-71254c2f1f3c)
